# Generated by Django 6.0.5 on 2026-05-21 00:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('student', 'Student'), ('premium', 'Premium'), ('institutional', 'Institutional')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('semester', 'Semester'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('max_downloads', models.IntegerField(default=-1, help_text='-1 means unlimited')),
                ('max_projects_access', models.IntegerField(default=-1)),
                ('can_access_premium', models.BooleanField(default=False)),
                ('can_publish', models.BooleanField(default=False)),
                ('has_analytics', models.BooleanField(default=False)),
                ('support_priority', models.CharField(default='basic', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('trial_days', models.IntegerField(default=0)),
                ('features', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloads_used', models.IntegerField(default=0)),
                ('projects_accessed', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
            ],
            options={
                'db_table': 'subscription_usage',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('trial', 'Trial'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_trial', models.BooleanField(default=False)),
                ('auto_renew', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
