# Generated by Django 6.0.5 on 2026-05-21 00:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_subscriptions', models.IntegerField(default=0)),
                ('new_subscriptions', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_projects', models.IntegerField(default=0)),
                ('new_projects', models.IntegerField(default=0)),
                ('total_downloads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'platform_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_views', models.IntegerField(default=0)),
                ('total_downloads', models.IntegerField(default=0)),
                ('total_bookmarks', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('monthly_views', models.JSONField(default=dict)),
                ('monthly_downloads', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_analytics',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('page_view', 'Page View'), ('project_view', 'Project View'), ('download', 'Download'), ('search', 'Search'), ('subscription', 'Subscription'), ('payment', 'Payment')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
