# Generated by Django 6.0.5 on 2026-05-21 09:46

from django.db import migrations, models


def backfill_project_codes(apps, schema_editor):
    Project = apps.get_model('marketplace', 'Project')
    counters = {}
    for project in Project.objects.order_by('created_at'):
        year = project.created_at.year
        counters[year] = counters.get(year, 0) + 1
        project.project_code = f'UDOM-{year}-{counters[year]:04d}'
        project.save(update_fields=['project_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_project_subscriptions'),
    ]

    operations = [
        # Step 1: add without unique so existing empty rows don't collide
        migrations.AddField(
            model_name='project',
            name='project_code',
            field=models.CharField(blank=True, editable=False, max_length=20, default=''),
            preserve_default=False,
        ),
        # Step 2: backfill existing rows
        migrations.RunPython(backfill_project_codes, migrations.RunPython.noop),
        # Step 3: now enforce uniqueness
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
