# Generated by Django 6.0.5 on 2026-05-23 17:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_unique_project_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='download',
            unique_together={('user', 'project')},
        ),
    ]
