# Generated by Django 6.0.5 on 2026-05-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_download_unique_per_user_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('fyp', 'Final Year Project'), ('research', 'Research Project'), ('personal', 'Personal Project'), ('others', 'Others')], default='fyp', max_length=20),
        ),
    ]
