# Generated by Django 6.0.5 on 2026-05-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_add_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubscription',
            name='duration_days',
            field=models.IntegerField(choices=[(30, '1 Month'), (90, '3 Months'), (180, '6 Months'), (365, '1 Year')], default=30),
        ),
        migrations.AddField(
            model_name='projectsubscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsubscription',
            name='renewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
