# Generated by Django 6.0.5 on 2026-05-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_login_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
